//
//  DataDummies.swift
//  Travel ID
//
//  Created by Patricia Fiona on 01/08/21.
//

import Foundation
import UIKit

let recomendedPlace: [Int] = [3,7,9]

var galeries: [Galery] = [
    Galery(placeID: 1,
           placeImage: "https://asset.kompas.com/crops/7BAA_ly7b-MmcoKLamKOPBypZx8=/53x0:676x415/750x500/data/photo/2020/05/18/5ec278e912802.jpg"),
    Galery(placeID: 1,
           placeImage: "https://akcdn.detik.net.id/visual/2018/10/16/56ec3a2c-9983-4d6d-aae8-2914ac7d055b_169.jpeg?w=650"),
    Galery(placeID: 1,
           placeImage: "https://cdn-2.tstatic.net/travel/foto/bank/images/danau-kelimutu-nusa-tenggara-timur_20180125_185012.jpg"),
    Galery(placeID: 1,
           placeImage: "https://akcdn.detik.net.id/visual/2016/04/01/2507c9e7-72c9-406e-aa74-054c081674c1_169.jpg?w=650"),
    Galery(placeID: 2,
           placeImage: "https://upload.wikimedia.org/wikipedia/commons/a/ae/Indonesia_-_Lake_Toba_%2826224127503%29.jpg"),
    Galery(placeID: 2,
           placeImage: "https://maritim.go.id/konten/unggahan/2016/01/tongging-ok.jpg"),
    Galery(placeID: 2,
           placeImage: "https://koran-jakarta.com/images/article/phpbzvgmg_resized.jpg"),
    Galery(placeID: 2,
           placeImage: "https://awsimages.detik.net.id/community/media/visual/2020/09/13/danau-toba_169.jpeg?w=780&q=80"),
    Galery(placeID: 3,
           placeImage: "https://asset.kompas.com/crops/oUbd-oWgmK9GQitYBij1i8DX-1Y=/0x73:1280x713/750x500/data/photo/2019/07/24/5d37bf7ba9d0f.jpg"),
    Galery(placeID: 3,
           placeImage: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7d/Mount_Bromo_at_sunrise%2C_showing_its_volcanoes_and_Mount_Semeru_%28background%29.jpg/1200px-Mount_Bromo_at_sunrise%2C_showing_its_volcanoes_and_Mount_Semeru_%28background%29.jpg"),
    Galery(placeID: 3,
           placeImage: "https://blue.kumparan.com/image/upload/fl_progressive,fl_lossy,c_fill,q_auto:best,w_640/v1598343691/pe2jv1eqlxxtrfusftm2.jpg"),
    Galery(placeID: 3,
           placeImage: "https://asset.kompas.com/crops/jNJCw78jRpATerjMmadbBwqblkE=/0x0:1800x1200/750x500/data/photo/2021/05/10/6099375e04acb.jpg"),
    Galery(placeID: 3,
           placeImage: "https://awsimages.detik.net.id/community/media/visual/2020/08/16/puncak-seruni-gunung-bromo-2_169.jpeg?w=780&q=90"),
    Galery(placeID: 4,
           placeImage: "https://www.pegipegi.com/travel/wp-content/uploads/2015/04/bunaken-.jpg"),
    Galery(placeID: 4,
           placeImage: "https://cdn.wonderin.id/statics/assets/uploads/08-12-20/Bunaken%20(rescale).jpg"),
    Galery(placeID: 4,
           placeImage: "https://www.gocelebes.com/wp-content/uploads/2013/01/keindahan-taman-laut-bunakan.jpg"),
    Galery(placeID: 4,
           placeImage: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTGpKk6DIZ_ejpzRwDMALm1W4IwuZso8NUKNCDuCI-5UzlGlKcyTcbABdHdJoXghWrVXD0&usqp=CAU"),
    Galery(placeID: 4,
           placeImage: "https://cdn-brilio-net.akamaized.net/news/2016/07/29/87629/404217-bunaken-island.png"),
    Galery(placeID: 4,
           placeImage: "https://www.celebes.co/wp-content/uploads/2019/08/Taman-Laut-Bunaken.jpg"),
    Galery(placeID: 5,
           placeImage: "https://asset.kompas.com/crops/eIP2s99xXyYl2dhwW9hDQ6QxisY=/0x0:780x520/750x500/data/photo/2019/09/26/5d8c64544d656.jpg"),
    Galery(placeID: 5,
           placeImage: "https://awsimages.detik.net.id/community/media/visual/2019/06/14/d918d788-bf56-4fbf-9216-50e870a4368a_169.jpeg?w=780&q=90"),
    Galery(placeID: 5,
           placeImage: "https://asset-a.grid.id/crop/0x0:0x0/700x465/photo/2019/08/06/960652103.jpg"),
    Galery(placeID: 6,
           placeImage: "https://asset.kompas.com/crops/_c-NhAebk_G0_y40134fG_TvEm8=/0x0:780x520/750x500/data/photo/2019/08/21/5d5ccedb6f21e.jpg"),
    Galery(placeID: 6,
           placeImage: "https://cdn.popbela.com/content-images/post/20200727/24fbfb96383848dd1a61782960992267_750x500.png"),
    Galery(placeID: 6,
           placeImage: "https://static.tokopedia.net/blog/wp-content/uploads/2019/09/wisata-dieng-2-Tribunnews.jpg"),
    Galery(placeID: 6,
           placeImage: "https://ugm.ac.id/galleries/crop/14136--730x420px.jpg"),
    Galery(placeID: 7,
           placeImage: "https://cdn1-production-images-kly.akamaized.net/Z51OrbC4MssukGpuQ37H0_MMTPU=/640x640/smart/filters:quality(75):strip_icc():format(jpeg)/kly-media-production/medias/2999392/original/000419100_1576642766-Fenita_1.jpg"),
    Galery(placeID: 7,
           placeImage: "https://awsimages.detik.net.id/community/media/visual/2019/02/28/e27d496c-d76b-4415-8cc3-d1131c07215f_169.jpeg?w=780&q=90"),
    Galery(placeID: 8,
           placeImage: "https://statik.tempo.co/data/2016/11/08/id_554381/554381_620.jpg"),
    Galery(placeID: 8,
           placeImage: "https://borneo24.com/wp-content/uploads/2020/10/pulau-derawan.jpg"),
    Galery(placeID: 8,
           placeImage: "https://www.balipost.com/wp-content/uploads/2017/09/balipostcom_kepulauan-derawan-destinasi-cantik-penggoda-wisman-yachter_01-696x419.jpg"),
    Galery(placeID: 8,
           placeImage: "https://www.celebes.co/borneo/wp-content/uploads/2020/11/Pulau-Derawan.jpg"),
    Galery(placeID: 9,
           placeImage: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Kawah_Putih_Lake_from_the_viewing_platform%2C_Bandung_Regency%2C_2014-08-21.jpg/1200px-Kawah_Putih_Lake_from_the_viewing_platform%2C_Bandung_Regency%2C_2014-08-21.jpg"),
    Galery(placeID: 9,
           placeImage: "https://anekatempatwisata.com/wp-content/uploads/2020/12/Kawah-Putih-seratusnews.jpg"),
    Galery(placeID: 10,
           placeImage: "https://asset.kompas.com/data/photo/2016/08/27/1046485pantai-21780x390.jpg"),
    Galery(placeID: 10,
           placeImage: "https://highlight.id/wp-content/uploads/2018/09/Highlight_pantai-tanjung-tinggi-tempat-destinasi-wisata-bangka-belitung-terbaik-liburan-weekend-traveling_01.jpg"),
    Galery(placeID: 10,
           placeImage: "https://asset.kompas.com/crops/xCUusIvnwA9yOFy_W9BvMFlHcic=/159x0:849x460/750x500/data/photo/2019/11/11/5dc92d9d3adfa.jpg"),
    Galery(placeID: 10,
           placeImage: "https://www.belitungtours.com/asap/assets/asap/pages/setting/galery/images/17/200509172508_pantai-tanjung-tinggi-belitung_2.jpg"),
    Galery(placeID: 10,
           placeImage: "https://statik.tempo.co/data/2019/02/13/id_819164/819164_720.jpg"),
    Galery(placeID: 10,
           placeImage: "https://blog.tripcetera.com/id/wp-content/uploads/2020/01/pantai-tanjung-kelayang-credit-image-@v_johni.jpg"),
    
]
 
var reviews: [Review] = [
    Review(placeID: 1,
           photo: UIImage(named: "user_01")!,
           title: "Realy Love the View!",
           username: "Jacob Seed",
           description: "Sangat ingin pergi ke sana karena suasana yang nyaman dan indah..."),
    Review(placeID: 1,
           photo: UIImage(named: "user_03")!,
           title: "Tunggu waktu nih...",
           username: "Vincent Yoseph",
           description: "Kapan ya bisa ke tempat sebagus ini?"),
    Review(placeID: 2,
           photo: UIImage(named: "user_02")!,
           title: "Bagus banget!!!",
           username: "Drake",
           description: "Indonesia emang surganya tempat wisata. Ayo mari berkunjung...!"),
    Review(placeID: 2,
           photo: UIImage(named: "user_03")!,
           title: "Tenang dan Nyaman",
           username: "Vincent Yoseph",
           description: "Tenang dan nyaman suasana alamnya juga oke banget! Recomended!!!"),
    Review(placeID: 3,
           photo: UIImage(named: "user_05")!,
           title: "Dingin yang Terbayarkan...",
           username: "Catalina Ferguson",
           description: "Susasana dingin dikalahkan dengan pemandangan yang super bagus..."),
    Review(placeID: 4,
           photo: UIImage(named: "user_06")!,
           title: "Tunggu waktu nih...",
           username: "Thomas Gautama",
           description: "Kapan ya bisa ke tempat sebagus ini?"),
    Review(placeID: 5,
           photo: UIImage(named: "user_02")!,
           title: "Bagus banget!!!",
           username: "Drake",
           description: "Indonesia emang surganya tempat wisata. Ayo mari berkunjung...!"),
    Review(placeID: 5,
           photo: UIImage(named: "user_03")!,
           title: "Tenang dan Nyaman",
           username: "Vincent Yoseph",
           description: "Tenang dan nyaman suasana alamnya juga oke banget! Recomended!!!"),
    Review(placeID: 6,
           photo: UIImage(named: "user_04")!,
           title: "Tunggu akhir tahun ah...",
           username: "Avandy Jaya",
           description: "Kumpulin uang buat mampir ke sini ah... Pasti bagus banget deh."),
    Review(placeID: 6,
           photo: UIImage(named: "user_04")!,
           title: "Recomended Katanya...",
           username: "Avandy Jaya",
           description: "Kata temen kantor yang uda pernah kesana sih bagus banget katanya. Pokoknya seru deh..."),
    Review(placeID: 7,
           photo: UIImage(named: "user_02")!,
           title: "Bagus banget!!!",
           username: "Drake",
           description: "Indonesia emang surganya tempat wisata. Ayo mari berkunjung...!"),
    Review(placeID: 8,
           photo: UIImage(named: "user_03")!,
           title: "Tenang dan Nyaman",
           username: "Vincent Yoseph",
           description: "Tenang dan nyaman suasana alamnya juga oke banget! Recomended!!!"),
    Review(placeID: 9,
           photo: UIImage(named: "user_04")!,
           title: "Tunggu akhir tahun ah...",
           username: "Avandy Jaya",
           description: "Kumpulin uang buat mampir ke sini ah... Pasti bagus banget deh."),
    Review(placeID: 10,
           photo: UIImage(named: "user_04")!,
           title: "Recomended Katanya...",
           username: "Avandy Jaya",
           description: "Kata temen kantor yang uda pernah kesana sih bagus banget katanya. Pokoknya seru deh..."),
]
